### ISSUE TITLE
Roadmap request

### ISSUE THREAD

**Issue by 4mation-kyeates** [formapro/pvm#21]
I am interested in using this library, i noticed there are some breaking changes in master (between v0.2.4 and master) are there many more breaking changes planned for the next release? or have you thought about what might be left before you get to version 1 of this library?

**Comment by makasim** [comment]
There is no roadmap, the code is quite stable and used in production. The minor version change (for example 0.2.4 -> 0.2.5) is BC compatible (should be at least). We raise the patch version when we have to do BC break (for example 0.2.5 -> 0.3.0).
