### ISSUE TITLE
examples is doesn't work

### ISSUE THREAD

**Issue by ova1900** [formapro/pvm#23]
i follow the docs to examples ,but  is  doesn't work ,the error strack :

2018-09-27 09:03:54[debug] [ProcessEngine] Start execution: process: 6cb01eda-b421-495f-8f95-fe835fb5c6f8, token: 1b075e07-7c54-4b7
f-a169-a93722b0a180

Fatal error: Uncaught TypeError: Return value of Formapro\Pvm\Token::getCurrentTransition() must be an instance of Formapro\Pvm\Tok
enTransition, null returned in D:\pvm\src\Token.php:80
Stack trace:
#0 D:\pvm\src\ProcessEngine.php(97): Formapro\Pvm\Token->getCurrentTransition()
#1 D:\pvm\src\ProcessEngine.php(78): Formapro\Pvm\ProcessEngine->doProceed(Object(Formapro\Pvm\Token))
#2 D:\pvm\demo\demo1.php(39): Formapro\Pvm\ProcessEngine->proceed(Object(Formapro\Pvm\Token), Object(Formapro\demo\EchoL
ogger))
#3 {main}
  thrown in D:\pvm\src\Token.php on line 80

**Comment by ova1900** [comment]
pvm version is :0.3.0

**Comment by makasim** [comment]
@ova1900 which one? also try to install 0.4.0 (I've just released it).

**Comment by ova1900** [comment]
sequence-example.md

thanks ,i will try 0.4.0

**Comment by ova1900** [comment]
the composer.json  install error 

    "require": {
        "php": "^7.0",
        "makasim/values": "0.5.x-dev",
        "ramsey/uuid": "^3",
        "psr/log": "^1"
    },


  Problem 1
    - The requested package makasim/values 0.5.x-dev exists as makasim/values[0.
1.0, 0.1.x-dev, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0
.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, dev-fix-tz, dev-master, 0.4.x-dev] but these a
re rejected by your constraint.

makasim/values   no 0.5.x-dev

**Comment by ova1900** [comment]
and i change to 0.4.x-dev   ,install ok, bug run the example sequence,throw error:

`
Fatal error: Uncaught TypeError: Argument 3 passed to Makasim\Values\array_set() must be of the type array, null given, called in D
:\pvm\vendor\makasim\values\src\functions\objects.php on line 81 and defined in D:\pvm\vendor\makasim\values\
src\functions\array.php:31
Stack trace:
#0 D:\pvm\vendor\makasim\values\src\functions\objects.php(81): Makasim\Values\array_set('transitions.0', Object(Formapro
\Pvm\TokenTransition), NULL)
#1 [internal function]: Formapro\Pvm\Token->Makasim\Values\{closure}('transitions', Object(Formapro\Pvm\TokenTransition), 0)
#2 D:\pvm\vendor\makasim\values\src\functions\objects.php(87): Closure->call(Object(Formapro\Pvm\Token), 'transitions',
Object(Formapro\Pvm\TokenTransition), NULL)
#3 D:\pvm\src\Token.php(66): Makasim\Values\add_object(Object(Formapro\Pvm\Token), 'transitions', Object(Formapro\Pvm\To
kenTransition))
#4 D:\pvm\src\ProcessEngine.php(267): Formapro\Pvm\Token->addTransition(Object(Formapro\Pvm\TokenTransition))
#5 D:\l in D:\pvm\vendor\makasim\values\src\functions\array.php on line 31
`

**Comment by ova1900** [comment]
@makasim

**Comment by makasim** [comment]
Could you please try examples from site https://pvm-demo.forma-pro.com/demo/sequence

They are executed there for real and therefor should work

**Comment by ova1900** [comment]
@makasim 
i follow  the pvm-demo.forma-pro.com/demo, got this error:

`
D:\pvm-sequence>composer req formapro/pvm:0.4.x-dev makasim/values:0.
5.x-dev
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package formapro/pvm 0.4.x-dev exists as formapro/pvm[0.1.0,
 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.
2.4, dev-master, 0.3.x-dev] but these are rejected by your constraint.
  Problem 2
    - The requested package makasim/values 0.5.x-dev exists as makasim/values[0.
1.0, 0.1.x-dev, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0
.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, dev-fix-tz, dev-master, 0.4.x-dev] but these a
re rejected by your constraint.


Installation failed, reverting ./composer.json to its original content.

`

**Comment by ova1900** [comment]
https://github.com/makasim/values/releases    

no  0.5.x-dev

**Comment by makasim** [comment]
@ova1900 there is no release yet but the current master is 0.5.x 

https://packagist.org/packages/makasim/values#dev-master

**Comment by ova1900** [comment]
oh......I found out the problem. The original problem is that my composer URL has problems, which leads to no 0.5.x-dev. i change to https://packagist.org   is work!
 thank you @makasim
