### ISSUE TITLE
missing trait

### ISSUE THREAD

**Issue by pulyavin** [formapro/pvm#7]
trait CreateTrait must be placed in Yadm directory. But now it just in src/ directory

**Comment by makasim** [comment]
does this commit https://github.com/formapro/pvm/commit/f008361a612ad0e2951276c0292f09bee31501df fixes the issue ?

**Comment by pulyavin** [comment]
kind of, but i migrated to 0.1.3 version for a while

**Comment by makasim** [comment]
tagged 0.1.5 (contains the fix)
